//
//  wkview.m
//  Translate
//
//  Created by xiaocong lin  on 2022/5/10.
//  Copyright © 2022 . All rights reserved.
//

#import "QLwkview.h"
@interface QLwkview ()
@end

@implementation QLwkview



- (UIView *)content{
    if (!_content) {
        _content = [UIView new];
        _content.frame = CGRectMake(5, 30, MAIN_SCREEN_WIDTH-10, MAIN_SCREEN_HEIGHT-60);
        _content.backgroundColor = [UIColor whiteColor];
        _content.layer.cornerRadius = 10;
        _content.layer.masksToBounds = YES;
    }
    return  _content;
}


- (UILabel *)lbale2{
    if (!_lbale2) {
        _lbale2 = [UILabel new];
        _lbale2.frame = CGRectMake(0, 20, self.content.frame.size.width, 20);
        _lbale2.textColor = RBGColor(155,95,86,1);
        _lbale2.textAlignment = NSTextAlignmentCenter;
        _lbale2.font = [UIFont systemFontOfSize:15];
        _lbale2.numberOfLines = 0;
    }
    return _lbale2;
}





- (UIButton *) button1{
    if (!_button1) {
        _button1 = [UIButton new];
        
        NSString *imagesetr = @"/9j/4AAQSkZJRgABAgEASABIAAD/4QDKRXhpZgAATU0AKgAAAAgABgESAAMAAAABAAEAAAEaAAUAAAABAAAAVgEbAAUAAAABAAAAXgEoAAMAAAABAAIAAAITAAMAAAABAAEAAIdpAAQAAAABAAAAZgAAAAAAAADYAAAAAQAAANgAAAABAAeQAAAHAAAABDAyMjGRAQAHAAAABAECAwCgAAAHAAAABDAxMDCgAQADAAAAAQABAACgAgAEAAAAAQAAAEWgAwAEAAAAAQAAAEWkBgADAAAAAQAAAAAAAAAAAAD/4hGsSUNDX1BST0ZJTEUAAQEAABGcYXBwbAIAAABtbnRyR1JBWVhZWiAH3AAIABcADwAuAA9hY3NwQVBQTAAAAABub25lAAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLWFwcGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVkZXNjAAAAwAAAAHlkc2NtAAABPAAACBpjcHJ0AAAJWAAAACN3dHB0AAAJfAAAABRrVFJDAAAJkAAACAxkZXNjAAAAAAAAAB9HZW5lcmljIEdyYXkgR2FtbWEgMi4yIFByb2ZpbGUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbWx1YwAAAAAAAAAfAAAADHNrU0sAAAAuAAABhGRhREsAAAA6AAABsmNhRVMAAAA4AAAB7HZpVk4AAABAAAACJHB0QlIAAABKAAACZHVrVUEAAAAsAAACrmZyRlUAAAA+AAAC2mh1SFUAAAA0AAADGHpoVFcAAAAaAAADTGtvS1IAAAAiAAADZm5iTk8AAAA6AAADiGNzQ1oAAAAoAAADwmhlSUwAAAAkAAAD6nJvUk8AAAAqAAAEDmRlREUAAABOAAAEOGl0SVQAAABOAAAEhnN2U0UAAAA4AAAE1HpoQ04AAAAaAAAFDGphSlAAAAAmAAAFJmVsR1IAAAAqAAAFTHB0UE8AAABSAAAFdm5sTkwAAABAAAAFyGVzRVMAAABMAAAGCHRoVEgAAAAyAAAGVHRyVFIAAAAkAAAGhmZpRkkAAABGAAAGqmhySFIAAAA+AAAG8HBsUEwAAABKAAAHLmFyRUcAAAAsAAAHeHJ1UlUAAAA6AAAHpGVuVVMAAAA8AAAH3gBWAWEAZQBvAGIAZQBjAG4A4QAgAHMAaQB2AOEAIABnAGEAbQBhACAAMgAsADIARwBlAG4AZQByAGkAcwBrACAAZwByAOUAIAAyACwAMgAgAGcAYQBtAG0AYQAtAHAAcgBvAGYAaQBsAEcAYQBtAG0AYQAgAGQAZQAgAGcAcgBpAHMAbwBzACAAZwBlAG4A6AByAGkAYwBhACAAMgAu ADIAQx6lAHUAIABoAOwAbgBoACAATQDgAHUAIAB4AOEAbQAgAEMAaAB1AG4AZwAgAEcAYQBtAG0AYQAgADIALgAyAFAAZQByAGYAaQBsACAARwBlAG4A6QByAGkAYwBvACAAZABhACAARwBhAG0AYQAgAGQAZQAgAEMAaQBuAHoAYQBzACAAMgAsADIEFwQwBDMEMAQ7BEwEPQQwACAARwByAGEAeQAtBDMEMAQ8BDAAIAAyAC4AMgBQAHIAbwBmAGkAbAAgAGcA6QBuAOkAcgBpAHEAdQBlACAAZwByAGkAcwAgAGcAYQBtAG0AYQAgADIALAAyAMEAbAB0AGEAbADhAG4AbwBzACAAcwB6APwAcgBrAGUAIABnAGEAbQBtAGEAIAAyAC4AMpAadShwcJaOUUlepgAyAC4AMoJyX2ljz4/wx3y8GAAg1ozAyQAgrBC5yAAgADIALgAyACDVBLhc0wzHfABHAGUAbgBlAHIAaQBzAGsAIABnAHIA5QAgAGcAYQBtAG0AYQAgADIALAAyAC0AcAByAG8AZgBpAGwATwBiAGUAYwBuAOEAIAFhAGUAZADhACAAZwBhAG0AYQAgADIALgAyBdIF0AXeBdQAIAXQBeQF1QXoACAF2wXcBdwF2QAgADIALgAyAEcAYQBtAGEAIABnAHIAaQAgAGcAZQBuAGUAcgBpAGMBAwAgADIALAAyAEEAbABsAGcAZQBtAGUAaQBuAGUAcwAgAEcAcgBhAHUAcwB0AHUAZgBlAG4ALQBQAHIAbwBmAGkAbAAgAEcAYQBtAG0AYQAgADIALAAyAFAAcgBvAGYAaQBsAG8AIABnAHIAaQBnAGkAbwAgAGcAZQBuAGUAcgBpAGMAbwAgAGQAZQBsAGwAYQAgAGcAYQBtAG0AYQAgADIALAAyAEcAZQBuAGUAcgBpAHMAawAgAGcAcgDlACAAMgAs ADIAIABnAGEAbQBtAGEAcAByAG8AZgBpAGxmbpAacHBepnz7ZXAAMgAuADJjz4/w ZYdO9k4AgiwwsDDsMKQwrDDzMN4AIAAyAC4AMgAgMNcw7TDVMKEwpDDrA5MDtQO9A7kDugPMACADkwO6A8EDuQAgA5MDrAO8A7wDsQAgADIALgAyAFAAZQByAGYAaQBsACAAZwBlAG4A6QByAGkAYwBvACAAZABlACAAYwBpAG4AegBlAG4AdABvAHMAIABkAGEAIABHAGEAbQBtAGEAIAAyACwAMgBBAGwAZwBlAG0AZQBlAG4AIABnAHIAaQBqAHMAIABnAGEAbQBtAGEAIAAyACwAMgAtAHAAcgBvAGYAaQBlAGwAUABlAHIAZgBpAGwAIABnAGUAbgDpAHIAaQBjAG8AIABkAGUAIABnAGEAbQBtAGEAIABkAGUAIABnAHIAaQBzAGUAcwAgADIALAAyDiMOMQ4HDioONQ5BDgEOIQ4hDjIOQA4BDiMOIg5MDhcOMQ5IDicORA4bACAAMgAuADIARwBlAG4AZQBsACAARwByAGkAIABHAGEAbQBhACAAMgAsADIAWQBsAGUAaQBuAGUAbgAgAGgAYQByAG0AYQBhAG4AIABnAGEAbQBtAGEAIAAyACwAMgAgAC0AcAByAG8AZgBpAGkAbABpAEcAZQBuAGUAcgBpAQ0AawBpACAARwByAGEAeQAgAEcAYQBtAG0AYQAgADIALgAyACAAcAByAG8AZgBpAGwAVQBuAGkAdwBlAHIAcwBhAGwAbgB5ACAAcAByAG8AZgBpAGwAIABzAHoAYQByAG8BWwBjAGkAIABnAGEAbQBtAGEAIAAyACwAMgY6BicGRQYnACAAMgAuADIAIAZEBkgGRgAgBjEGRQYnBi8GSgAgBjkGJwZFBB4EMQRJBDAETwAgBEEENQRABDAETwAgBDMEMAQ8BDwEMAAgADIALAAyAC0EPwRABD4ERAQ4BDsETABHAGUAbgBlAHIAaQBjACAARwBy AGEAeQAgAEcAYQBtAG0AYQAgADIALgAyACAAUAByAG8AZgBpAGwAZQAAdGV4dAAAAABDb3B5cmlnaHQgQXBwbGUgSW5jLiwgMjAxMgAAWFlaIAAAAAAAAPNRAAEAAAABFsxjdXJ2AAAAAAAABAAAAAAFAAoADwAUABkAHgAjACgALQAyADcAOwBAAEUASgBPAFQAWQBeAGMAaABtAHIAdwB8AIEAhgCLAJAAlQCaAJ8ApACpAK4AsgC3ALwAwQDGAMsA0ADVANsA4ADlAOsA8AD2APsBAQEHAQ0BEwEZAR8BJQErATIBOAE+AUUBTAFSAVkBYAFnAW4BdQF8AYMBiwGSAZoBoQGpAbEBuQHBAckB0QHZAeEB6QHyAfoCAwIMAhQCHQImAi8COAJBAksCVAJdAmcCcQJ6AoQCjgKYAqICrAK2AsECywLVAuAC6wL1AwADCwMWAyEDLQM4A0MDTwNaA2YDcgN+A4oDlgOiA64DugPHA9MD4APsA/kEBgQTBCAELQQ7BEgEVQRjBHEEfgSMBJoEqAS2BMQE0wThBPAE/gUNBRwFKwU6BUkFWAVnBXcFhgWWBaYFtQXFBdUF5QX2BgYGFgYnBjcGSAZZBmoGewaMBp0GrwbABtEG4wb1BwcHGQcrBz0HTwdhB3QHhgeZB6wHvwfSB+UH+AgLCB8IMghGCFoIbgiCCJYIqgi+CNII5wj7CRAJJQk6CU8JZAl5CY8JpAm6Cc8J5Qn7ChEKJwo9ClQKagqBCpgKrgrFCtwK8wsLCyILOQtRC2kLgAuYC7ALyAvhC/kMEgwqDEMMXAx1DI4MpwzADNkM8w0NDSYNQA1aDXQNjg2pDcMN3g34DhMOLg5JDmQOfw6bDrYO0g7uDwkPJQ9BD14Peg+WD7MPzw/sEAkQJhBDEGEQfhCbELkQ1xD1ERMRMRFPEW0RjBGqEckR6BIHEiYSRRJkEoQSoxLDEuMTAxMjE0MTYxODE6QTxRPlFAYUJxRJFGoUixStFM4U8BUSFTQVVhV4FZsVvRXgFgMWJhZJFmwWjxayFtYW+hcdF0EXZReJF64X0hf3GBsYQBhlGIoYrxjV GPoZIBlFGWsZkRm3Gd0aBBoqGlEadxqeGsUa7BsUGzsbYxuKG7Ib2hwCHCocUhx7HKMczBz1HR4dRx1wHZkdwx3sHhYeQB5qHpQevh7pHxMfPh9pH5Qfvx/qIBUgQSBsIJggxCDwIRwhSCF1IaEhziH7IiciVSKCIq8i3SMKIzgjZiOUI8Ij8CQfJE0kfCSrJNolCSU4JWgllyXHJfcmJyZXJocmtyboJxgnSSd6J6sn3CgNKD8ocSiiKNQpBik4KWspnSnQKgIqNSpoKpsqzysCKzYraSudK9EsBSw5LG4soizXLQwtQS12Last4S4WLkwugi63Lu4vJC9aL5Evxy/+MDUwbDCkMNsxEjFKMYIxujHyMioyYzKbMtQzDTNGM38zuDPxNCs0ZTSeNNg1EzVNNYc1wjX9Njc2cjauNuk3JDdgN5w31zgUOFA4jDjIOQU5Qjl/Obw5+To2OnQ6sjrvOy07azuqO+g8JzxlPKQ84z0iPWE9oT3gPiA+YD6gPuA/IT9hP6I/4kAjQGRApkDnQSlBakGsQe5CMEJyQrVC90M6Q31DwEQDREdEikTORRJFVUWaRd5GIkZnRqtG8Ec1R3tHwEgFSEtIkUjXSR1JY0mpSfBKN0p9SsRLDEtTS5pL4kwqTHJMuk0CTUpNk03cTiVObk63TwBPSU+TT91QJ1BxULtRBlFQUZtR5lIxUnxSx1MTU19TqlP2VEJUj1TbVShVdVXCVg9WXFapVvdXRFeSV+BYL1h9WMtZGllpWbhaB1pWWqZa9VtFW5Vb5Vw1XIZc1l0nXXhdyV4aXmxevV8PX2Ffs2AFYFdgqmD8YU9homH1YklinGLwY0Njl2PrZEBklGTpZT1lkmXnZj1mkmboZz1nk2fpaD9olmjsaUNpmmnxakhqn2r3a09rp2v/bFdsr20IbWBtuW4SbmtuxG8eb3hv0XArcIZw4HE6cZVx8HJLcqZzAXNdc7h0FHRwdMx1KHWFdeF2Pnabdvh3VnezeBF4bnjMeSp5iXnnekZ6pXsEe2N7wnwhfIF84X1BfaF+AX5ifsJ/I3+Ef+WAR4CogQqBa4HNgjCCkoL0g1eDuoQdhICE44VHhauGDoZyhteHO4efiASIaYjOiTOJmYn+imSKyoswi5aL/IxjjMqNMY2Yjf+OZo7OjzaPnpAGkG6Q1pE/kaiSEZJ6kuOTTZO2lCCUipT0lV+VyZY0lp+XCpd1l+CYTJi4mSSZkJn8mmia1ZtCm6+cHJyJnPedZJ3SnkCerp8dn4uf+qBpoNihR6G2oiailqMGo3aj5qRWpMelOKWpphqmi6b9p26n4KhSqMSpN6mpqhyqj6sCq3Wr6axcrNCtRK24ri2uoa8Wr4uwALB1sOqxYLHWskuywrM4s660JbSctRO1irYBtnm28Ldot+C4WbjRuUq5wro7urW7LrunvCG8m70VvY++Cr6Evv+/er/1wHDA7MFnwePCX8Lbw1jD1MRRxM7FS8XIxkbGw8dBx7/IPci8yTrJuco4yrfLNsu2zDXMtc01zbXONs62zzfPuNA50LrRPNG+0j/SwdNE08bUSdTL1U7V0dZV1tjXXNfg2GTY6Nls2fHadtr724DcBdyK3RDdlt4c3qLfKd+v4DbgveFE4cziU+Lb42Pj6+Rz5PzlhOYN5pbnH+ep6DLovOlG6dDqW+rl63Dr++yG7RHtnO4o7rTvQO/M8Fjw5fFy8f/yjPMZ86f0NPTC9VD13vZt9vv3ivgZ+Kj5OPnH+lf65/t3/Af8mP0p/br+S/7c/23////AAAsIAEUARQEBEQD/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/3QAEAAn/2gAIAQEAAD8A/Wpn/aD/AOCXX7QbM7S+IvBPiOUuzM1xb+Eviz4St7nLMWP2oaN4w0YXOWJ+0aj4d1G4yf7W8O6t/wATn+jH4IfG/wCH/wC0F8P9J+I3w51ZdQ0jUF8i+sZ/Li1jw7rEUcb3ug69ZJJIbLVLIyJvXdJb3VvJb6hYXF1p93a3MvrtFFFFfmF+3z+3zpf7POl3nwy+GV5Zav8AGvV7LFxcDybyw+G9heQ7otU1SIiWG58SXMDrNoehzho4Y3i1jWITYmxsda/N/wDZw/4Jv/F79pLwnqHxh+IXxB1P4dL4yvxq+hXOtaXe+IPE3jWC9a5ur/xXqiTavplxa2eoXE0cuk3d5NcXetJLdakIYdPfTrvUv//Q/ub+N/wQ+H/7QXw/1b4c/EbSRqGkagPPsL+Dy4tY8O6xFHKllr2g3rxSmy1SyMrhXKSW91byXGn6hb3enXl1bS/zmf8AGQP/AAS2/aA53+IPA3iB/wDpva+D/iv4Qtrj/t6XRPF2ircf9PGoeHNQuP8AmK+HNVH9tf0Z/BD43/D/APaC+H+k/Eb4c6suoaRqC+RfWM/lxax4d1iKON73QdeskkkNlqlkZE3rukt7q3kt9QsLi60+7tbmX12iivzC/b5/b50v9nnS7z4ZfDK8stX+Ner2WLi4Hk3lh8N7C8h3RapqkREsNz4kuYHWbQ9DnDRwxvFrGsQmxNjY618ZfsE/sE6v8WdXtv2kf2kba/1Pw/qd+3iTwt4W8SNNdal8Q9Supzef8Jh4w+2NJcT+G57hzd2Njdky+LJWF9e48PGOLX/6CERI0SONFjjRVRERQqIigBURVAVVUABVAAAAAAxiv//R/v4ryL43/BD4f/tBfD/Vvhz8RtJXUNI1BfPsb6Dy4tY8O6xFHIllr2g3rxyGy1SyMj7G2yW91byXGn39vdafd3VtL/Ob/wAZA/8ABLb9oD+PxB4G8QP/ANN7Xwh8V/CFtcf9vS6J4u0Vbj/p41Dw5qFx/wAxXw7qv/E6/oy+CHxv+H/7QXw/0n4jfDnVl1DSNQXyL6xn8uLWPDusRRxve6Dr1kkkhstUsjIm9d0lvdW8lvqFhcXWn3drcy+u1+YX7fP7fOl/s86XefDL4ZXllq/xr1eyxcXA8m8sPhvYXkO6LVNUiIlhufElzA6zaHoc4aOGN4tY1iE2JsbHWvjL9gn9gnV/izq9t+0j+0jbX+p+H9Tv28SeFvC3iRprrUviHqV1Obz/AITDxh9saS4n8Nz3Dm7sbG7Jl8WSsL69x4eMcWv/ANBCIkaJHGixxoqoiIoVERQAqIqgKqqAAqgAAAAAYxTq/9L+/iivIvjf8EPh/wDtBfD/AFb4c/EbSV1DSNQXz7G+g8uLWPDusRRyJZa9oN68chstUsjI+xtslvdW8lxp9/b3Wn3d1bS/zm/8ZA/8Etv2gP4/EHgbxA//AE3tfCHxX8IW1x/29Loni7RVuP8Ap41Dw5qFx/zFfDuq/wDE6/QX9pb/AIKpeANL+Eehyfs+351j4lfEDRWuFfUbML/wquB2ltLx/EFnKsttc+Lbe5inh0jSkkvNNYRx6/dS3Wjy6Xb698//ALBP7BOr/FnV7b9pH9pG2v8AU/D+p37eJPC3hbxI011qXxD1K6nN5/wmHjD7Y0lxP4bnuHN3Y2N2TL4slYX17jw8Y4tf/oIREjRI40WONFVERFCoiKAFRFUBVVQAFUAAAAADGKdRX//T/v4oor8df+CqX7S3wj0v4f3/AOz7Joei/ED4lawbLUnW4ZpIPhWVAls/EEl5aSxXNv4tubWR49J0iG4iDabdzXWvxS6Pd2+ma9+Ifh3w94n+B3ij4QfFD4ofCC41zwTrlxZ+MtA0HxlZ3lh4f+IHh+xvPLnjjnT7yNiG8ggvYZ4JrefSb+/0rVPD2qQw6h/XP8DfjZ8PPj98PNH+IXw21OO90S9jW1u9OkWKDVfDWqwRRG78Pa5YRySCw1Kw8xAY1Z7a5tnt7/T57rTru0uX9foor//U/v4or8wv2+f2+dL/AGedLvPhl8Mryy1f416vZYuLgeTeWHw3sLyHdFqmqRESw3PiS5gdZtD0OcNHDG8WsaxCbE2NjrXxl+wT+wTq/wAWdXtv2kf2kba/1Pw/qd+3iTwt4W8SNNdal8Q9Supzef8ACYeMPtjSXE/hue4c3djY3ZMviyVhfXuPDxji1/8Aav42fA34efH74ean8NviFo8d5ol5Gsmm3dqsUGq+GtVgikjsNc8PXZik+walYCRljIje2ubZ59Ov7a6067urV/5zv+Mgf+CW37QODv8AEHgbxA//AE3tfB/xY8IWtx2/4+l0Txdoi3Hrcah4c1C4/wCYt4c1Uf2z/Rn8EPjf8P8A9oL4f6T8Rvhzqy6hpGoL5F9Yz+XFrHh3WIo43vdB16ySSQ2WqWRkTeu6S3ureS31CwuLrT7u1uZfXaK//9X+/ivzC/b5/b50v9nnS7z4ZfDK8stX+Ner2WLi4Hk3lh8N7C8h3RapqkREsNz4kuYHWbQ9DnDRwxvFrGsQmxNjY618ZfsE/sE6v8WdXtv2kf2kba/1Pw/qd+3iTwt4W8SNNdal8Q9Supzef8Jh4w+2NJcT+G57hzd2Njdky+LJWF9e48PGOLX/AOghESNEjjRY40VUREUKiIoAVEVQFVVAAVQAAAAAMYp1eRfG/wCCHw//AGgvh/q3w5+I2kjUNI1AefYX8Hlxax4d1iKOVLLXtBvXilNlqlkZXCuUkt7q3kuNP1C3u9OvLq2l/nM/4yB/4JbftA4O/wAQeBvED/8ATe18H/Fjwha3Hb/j6XRPF2iLcetxqHhzULj/AJi3hzVR/bP9GfwQ+N/w/wD2gvh/pPxG+HOrLqGkagvkX1jP5cWseHdYijje90HXrJJJDZapZGRN67pLe6t5LfULC4utPu7W5l9dr//W/q7/AG+f2+dL/Z50u8+GXwyvLLV/jXq9li4uB5N5YfDewvId0WqapERLDc+JLmB1m0PQ5w0cMbxaxrEJsTY2OtfGX7BP7BOr/FnV7b9pH9pG2v8AU/D+p37eJPC3hbxI011qXxD1K6nN5/wmHjD7Y0lxP4bnuHN3Y2N2TL4slYX17jw8Y4tf/oIREjRI40WONFVERFCoiKAFRFUBVVQAFUAAAAADGKdRRXkXxv8Agh8P/wBoL4f6t8OfiNpI1DSNQHn2F/B5cWseHdYijlSy17Qb14pTZapZGVwrlJLe6t5LjT9Qt7vTry6tpf5zf+Mgf+CW37QH8fiDwN4gf/pva+EPiv4Qtrj/ALel0Txdoq3H/TxqHhzULj/mK+HdV/4nX9GXwQ+N/wAP/wBoL4f6T8Rvhzqy6hpGoL5F9Yz+XFrHh3WIo43vdB16ySSQ2WqWRkTeu6S3ureS31CwuLrT7u1uZf/X/Zv/AIJv/s4eE/2kvi98QfiF8YdQv/GS/DrU9M1q50LVw17B418TeIL3V5k1TxXf3VzNcahZ2txpk15d6TLHImtXdxENSu20+G807VP6W0RI0SONFjjRVRERQqIigBURVAVVUABVAAAAAAxinUUUUV5F8b/gh8P/ANoL4f6t8OfiNpK6hpGoL59jfQeXFrHh3WIo5Este0G9eOQ2WqWRkfY22S3ureS40+/t7rT7u6tpf5Mp5/iN8BviN8Vfh78Pfir4w8NxeG/GGo+GdS1LwzqOp+Gv+Ek/4RrU9W02xv7+x0zVtqOii5khhlurz7N9smjjmYMzN//Z";
        
        //Base64字符串转UIImage图片
        NSData *imageData = [[NSData alloc] initWithBase64EncodedString:imagesetr options:NSDataBase64DecodingIgnoreUnknownCharacters];
        UIImage *image1 = [UIImage imageWithData:imageData];
        
        
        _button1.frame =CGRectMake(self.content.frame.size.width - 40,20,20, 20);
        [_button1 addTarget:self action:@selector(btnAction:) forControlEvents:UIControlEventTouchUpInside];
        [_button1 setBackgroundImage:image1 forState:UIControlStateNormal];
    }
    return  _button1;
}


- (WKWebView *)wkview{
    
    if (!_wkview) {
        _wkview= [[WKWebView alloc] initWithFrame:CGRectMake(0,CGRectGetMaxY(self.lbale2.frame)+10, self.content.frame.size.width, self.content.frame.size.height-60)];
        _wkview.layer.cornerRadius = 10;
        _wkview.layer.masksToBounds = YES;
        _wkview.backgroundColor = [UIColor whiteColor];
        _wkview.opaque = NO;
        _wkview.scrollView.alwaysBounceVertical = NO;
        _wkview.scrollView.alwaysBounceHorizontal = NO;
        _wkview.scrollView.bounces = NO;
    }


    return _wkview;
}

- (void)btnAction:(UIButton *)sender{
    
    
    [self hide];
    
}
- (void)loadHtml:(NSInteger )index{
    NSString *path1 =@"http://apks.0898richang.com/richang-protocol/%E6%9C%8D%E5%8A%A1%E5%8D%8F%E8%AE%AE.html";
    self.lbale2.text = @"服务协议";
        //加载本地 html js 文件
    if (index == 10) {//yinsi“”
        path1 =@"https://apisdk.020richang.com/storage/box/dist/#/PrivacyDetail";
        self.lbale2.text = @"隐私条款";
    }
    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:path1]];
    [self.wkview loadRequest:request];
    
      
}

- (void) show:(UIView *)fView tapIndex:(NSInteger )index {
    [fView addSubview:self];
    self.backgroundColor = [UIColor blackColor];
    [self addSubview:self.content];
    [self.content addSubview:self.wkview];
    [self.content addSubview:self.lbale2];
    [self.content addSubview:self.button1];
    __weak typeof (self) bSelf = self;
    
    [UIView animateWithDuration:0.1 animations:^{
        self.content.alpha = 1;
        [bSelf loadHtml:index];
    } completion:^(BOOL finished) {

    }];

}


-(void) hide{
    [UIView animateWithDuration:0.1 animations:^{
        self.content.alpha = 0;
    } completion:^(BOOL finished) {
        [self removeFromSuperview];
    }];
    
    
    
    
}

@end
